# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: mashweb.club
email: tom@mashweb.club
description: >- # This appears in the head meta and in feed.xml .
  demos & docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://doc.mashweb.club"
twitter_username: tomelam
github_username:  Mashweb

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: tom@mashweb.club
  facebook:
  flickr:
  github: Mashweb
  instagram:
  linkedin: tomelam
  pinterest:
  rss:
  twitter: tomelam
  stackoverflow: users/438912/tom-elam
  youtube: user/tomelam
  googleplus: u/0/104293723893521677134

# Build settings
# theme: minima
theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
