# Meta data
name:         Zen
authors:      Tom Elam
description:  Zen

# Dependencies
highlighter:  rouge

# Permalinks
permalink:    pretty

# Server
port:         4000
baseurl:      /zen
markdown:     kramdown

title: Zen
google_analytics: UA-83016942-1
show_downloads: true
theme: jekyll-theme-leap-day